name: CI
on: [pull_request]
jobs:
  tests:
    name: "${{ matrix.os }}: py${{ matrix.python-version }} sphinx: ${{ matrix.sphinx-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true  # Set on "false" to get the results of ALL builds
      matrix:
        os: ["ubuntu-latest"]
        # 3.9.8 seems to be broken with type_ast
        # https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1829077.html
        python-version: ["3.7, "3.8", "3.9.7", "3.10"]
        sphinx-version: ['5.0.2']
        sphinx-needs-version: ["0.7.9", "1.0.1", "1.0.2"]
        include:
          # Check only newest setups for win server
          - os: "windows-latest"
            python-version: "3.10"
            sphinx-version: "5.0.2"
            sphinx-needs-version: "1.0.2"
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Nox Dependencies
        run: |
          python -m pip install poetry nox nox-poetry
      - name: Install other dependencies
        run: |
          python -m pip install setuptools
      - name: Final package list
        run: |
          pip freeze

      - name: Run Tests on Windows
        run: nox --non-interactive --session "tests-${{ matrix.python-version }}(sphinx='${{ matrix.sphinx-version }}', sphinx_needs='${{ matrix.sphinx-needs-version }}')" -- --full-trace
        if: runner.os == 'Windows'

      - name: Run Tests on Linux
        run: nox --non-interactive --session "tests-${{ matrix.python-version }}(sphinx='${{ matrix.sphinx-version }}', sphinx_needs='${{ matrix.sphinx-needs-version }}')" -- --full-trace
        if: runner.os == 'Linux'

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install/Update  build dependencies
        run: |
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade pip
      - name: Install Poetry
        run: |
          curl -sL https://install.python-poetry.org | python -
      - name: Update Pip
        run: poetry run pip install -U pip setuptools
      - name: Install Dependencies
        run: poetry install
      - uses: pre-commit/action@v3.0.0
